name: Update OISD & anti-AD rules

on:
  schedule:
    # 每周一 00:00 UTC（北京时间周一 08:00）
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Clash classic lists (DOMAIN-SUFFIX)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p rules
          changed=0

          gen() {
            local name="$1" src="$2" out="rules/${name}.list"
            local tmp
            tmp="$(mktemp)"

            echo ">> Fetching ${name} from ${src}"
            curl -fsSL "$src" \
            | sed -e 's/^[[:space:]]*#.*$//' -e '/^[[:space:]]*$/d' \
                  -e 's/^\*\.\?//g' -e 's/^\.//g' \
            | grep -E '^[0-9a-z.-]+\.[a-z]{2,}$' \
            | sort -u \
            | awk '{print "DOMAIN-SUFFIX," $0}' > "$tmp"

            if [ ! -f "$out" ] || ! cmp -s "$tmp" "$out"; then
              mv "$tmp" "$out"
              echo "Updated $out ($(wc -l < "$out") lines)."
              changed=1
            else
              echo "No changes for $out."
              rm -f "$tmp"
            fi
          }

          # 1) OISD nsfw domains
          gen "oisd_nsfw" "https://raw.githubusercontent.com/sjhgvr/oisd/refs/heads/main/domainswild2_nsfw.txt"

          # 2) anti-AD domains
          gen "anti_ad" "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/refs/heads/master/anti-ad-domains.txt"

          if [ "$changed" -eq 1 ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add rules/oisd_nsfw.list rules/anti_ad.list
            git commit -m "chore: update ad rule lists ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          else
            echo "Nothing to commit."
          fi
